Depend on oldest-supported-numpy instead of plain NumPy
Blosc/python-blosc2 pull request #134
Opened 2023-09-26 09:21 UTC by ivilata

Requiring an oldest version of NumPy causes less incompatibilities with other projects (esp. if they depend on oldest-supported-numpy themselves).

Tests seem to work just fine, and generated documentation still looks ok.

2023-09-26 09:55 UTC, FrancescAlted commented on requirements-runtime.txt
> +oldest-supported-numpy
I think for runtime `numpy<2` is a better option (`oldest-supported-numpy` is mainly for building purposes).

2023-09-26 09:56 UTC, FrancescAlted requested changes

2023-09-26 09:56 UTC, FrancescAlted commented on requirements-test-wheels.txt
> +oldest-supported-numpy
Ditto

2023-09-26 09:56 UTC, FrancescAlted commented on requirements-tests.txt
> +oldest-supported-numpy
Ditto

2023-09-27 11:07 UTC, martaiborra approved these changes
LGTM

2023-09-27 11:39 UTC, FrancescAlted commented
I am doing the necessary changes for this in PR https://github.com/Blosc/python-blosc2/pull/135.  This can be closed now.

2023-09-27 11:39 UTC, closed without merging